namespace GrevHome.Navigation;

public enum Route
{
    FirstRunSetup,
    Login,
    CreateProfile,
    Dashboard,
    DashboardTileSettings,
    DashboardTileArtworkPicker,
    Friends,
    FriendProfile,
    FriendMessages,
    GrevDadWeb,
    ProfilePlayers,
    ProfileView,
    ProfileEdit,
    ProfileTiles,
    ProfilePhotoPicker,
    GameAdd,
    GameFilePicker,
    GameScan,
    GameSettings,
    GameArtworkPicker,
    GrevStore,
    GrevStoreApp,
    InstalledLibrary,
    AppSettings,
    AppArtworkPicker,
    RunningApps,
    AppKiller,
    Settings,
    AdminConsole,
    Files,
    ActivityCenter
}
